-- Seed Data for Templates
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('svg-sample', 'Gold Royal Border', 'Luxury gold border design from SVG', '#FFD700', NULL, '/templates/fancy-border.svg', 'centered', false, '{}', '{}', '{"companyName":"ROYAL PALACE","address":"1 Royal Way, Castle District","additionalText":["EST. 1800"]}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('modern', 'Modern Standard', 'Clean vertical layout with centered logo', '#ffffff', NULL, NULL, 'default', false, '{}', '{}', '{"companyName":"YOUR BRAND","address":"123 Main Street, City"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('corporate', 'Corporate Split', 'Logo on left, details on right', '#f8f9fa', NULL, NULL, 'split-left', false, '{}', '{}', '{"companyName":"CORPORATE INC","address":"Business District, City"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('bold', 'Bold Identity', 'Large logo with minimal text', '#2d3748', NULL, NULL, 'centered', false, '{}', '{}', '{"companyName":"BOLD","address":""}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('retail', 'Retail Banner', 'Horizontal layout optimized for shop boards', '#fff5f5', NULL, NULL, 'banner', false, '{}', '{}', '{"companyName":"STORE NAME","address":"Shop 12, Market Complex"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('classic', 'Classic Right', 'Logo on right, classic typography', '#fffaf0', NULL, NULL, 'split-right', false, '{}', '{}', '{"companyName":"Classic Co.","address":"Est. 1980"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('professional', 'Professional Border', 'Clean design with professional double border', '#ffffff', '/templates/professional.png', NULL, 'default', false, '{}', '{}', '{"companyName":"ATHMA","address":"#123, Street Name, City, State - 560001","additionalText":["ARCHITECTURE | INTERIORS"]}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('industrial', 'Industrial Dark', 'Dark theme with rivet details', '#333333', '/templates/industrial.png', NULL, 'centered', false, '{}', '{}', '{"companyName":"CRAFTBY","address":"Industrial Area, Phase 1","additionalText":["THE ART OF DESIGN"]}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('modern-split', 'Modern Side', 'Bold side strip layout', '#ffffff', '/templates/modern-split.png', NULL, 'split-left', false, '{}', '{}', '{"companyName":"VARAPRADA","address":"123 Business Park, Tech City, Bangalore - 560100","additionalText":["ENTERPRISES","GSTIN: 29ABCDE1234F1Z5"]}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('boxed', 'Boxed Frame', 'Simple framed layout for formal details', '#ffffff', '/templates/boxed.png', NULL, 'default', false, '{}', '{}', '{"companyName":"PWLO","address":"Premium World License Org, Official HQ","additionalText":["EST. 2024"]}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.templates (id, name, description, thumbnail_color, thumbnail, svg_path, layout_type, is_custom, components, fabric_config, defaults) VALUES ('foundation', 'Foundation Blue', 'Solid color background with white text', '#1e3a8a', '/templates/foundation.png', NULL, 'centered', false, '{}', '{}', '{"companyName":"IMW","address":"Industrial Manufacturing Works, Sector 45","additionalText":["SINCE 1995"]}') ON CONFLICT (id) DO NOTHING;
